version: 2

run:
  timeout: 10m
  tests: true
  build-tags:
    - all
  exclude-dirs:
    - tests/antithesis
  exclude-files:
    - ".*\\.pb\\.go$"

linters:
  enable:
    - govet
    - ineffassign
    - misspell
    - unconvert
    - gosec
    - staticcheck
  disable:
    - errcheck  # Too many legacy unchecked errors
  settings:
    gosec:
      excludes:
        - G107  # Potential HTTP request made with variable url
        - G404  # Use of weak random number generator

formatters:
  enable:
    - gofmt
    - goimports

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
    - path: tests/
      linters:
        - gosec
