run:
  timeout: 10m
  tests: true
  build-tags:
    - all
  skip-dirs:
    - tests/antithesis
  skip-files:
    - ".*\\.pb\\.go$"

linters:
  enable:
    - govet
    - gofmt
    - goimports
    - ineffassign
    - misspell
    - unconvert
    - gosec
    - staticcheck
    - gosimple

linters-settings:
  govet:
    check-shadowing: false
  gosec:
    excludes:
      - G107  # Potential HTTP request made with variable url
      - G404  # Use of weak random number generator

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
    - path: tests/
      linters:
        - gosec
