# BUILDER_IMAGE_TAG should identify the builder image
ARG BUILDER_IMAGE_TAG

# LUXD_NODE_IMAGE needs to identify an existing luxd node image and should include the tag
ARG LUXD_NODE_IMAGE

# ============= Compilation Stage ================
FROM antithesis-evm-builder:$BUILDER_IMAGE_TAG AS builder

# The builder workdir will vary between instrumented and non-instrumented builders
ARG BUILDER_WORKDIR

WORKDIR $BUILDER_WORKDIR

# Build the VM
RUN ./scripts/build.sh /build/srEXiWaHuhNyGwPUi444Tu47ZEDwxTWrbQiuD7FmgSAQ6X7Dy

# ============= Cleanup Stage ================
FROM $LUXD_NODE_IMAGE AS execution

# Copy identifying information into the container. This will replace
# the luxd commit hash in the base image.
COPY --from=builder /build/commit_hash.txt /luxd/build/commit_hash.txt

# Copy the antithesis dependencies into the container
COPY --from=builder /instrumented/symbols /symbols

# Configure the node with the location of the plugin
ENV LUXD_PLUGIN_DIR=/luxd/build/plugins

# Copy the executable into the container
COPY --from=builder $BUILDER_WORKDIR/build/srEXiWaHuhNyGwPUi444Tu47ZEDwxTWrbQiuD7FmgSAQ6X7Dy\
  $LUXD_PLUGIN_DIR/srEXiWaHuhNyGwPUi444Tu47ZEDwxTWrbQiuD7FmgSAQ6X7Dy

# The node image's entrypoint will be reused.
