# BUILDER_IMAGE_TAG should identify the builder image
ARG BUILDER_IMAGE_TAG

# LUXD_NODE_IMAGE needs to identify an existing luxd node image and should include the tag
ARG LUXD_NODE_IMAGE

# ============= Compilation Stage ================
FROM antithesis-evm-builder:$BUILDER_IMAGE_TAG AS builder

# The builder workdir will vary between instrumented and non-instrumented builders
ARG BUILDER_WORKDIR

WORKDIR $BUILDER_WORKDIR

# Build the workload
RUN ./scripts/build_antithesis_workload.sh

# ============= Cleanup Stage ================
# Base the workflow on the node image to support bootstrap testing
FROM $LUXD_NODE_IMAGE AS execution

# The builder workdir will vary between instrumented and non-instrumented builders
ARG BUILDER_WORKDIR

# Copy the executable into the container
COPY --from=builder $BUILDER_WORKDIR/build/workload ./workload

CMD [ "./workload" ]
