// Copyright (C) 2025-2026, Lux Industries Inc. All rights reserved.
// See the file LICENSE for licensing terms.

package core

// Process-level proof that wiring the Block-STM executor into StateProcessor
// (behind parallel.Enabled) is consensus-safe end to end. Unlike the executor's
// own determinism corpus (which compares roots in isolation), these tests drive
// real blocks through the FULL validation pipeline — InsertChain → Process →
// BlockValidator.ValidateState, which checks gas, bloom, the receipt-trie root
// AND the state root against each block's header. So a block accepted with the
// flag ON is proof the parallel path produced byte-identical state AND receipts.
//
// The blocks are generated by the sequential chain maker, so every header.Root is
// the sequential state root; inserting them with the flag ON forces ExecuteVerified
// to reproduce that exact root (and receipts) or the block is rejected.

import (
	"crypto/ecdsa"
	"math/big"
	"strings"
	"testing"

	"github.com/luxfi/crypto"
	"github.com/luxfi/evm/accounts/abi"
	"github.com/luxfi/evm/consensus/dummy"
	"github.com/luxfi/evm/core/parallel"
	"github.com/luxfi/evm/params"
	"github.com/luxfi/evm/plugin/evm/upgrade/legacy"
	"github.com/luxfi/geth/common"
	"github.com/luxfi/geth/core/rawdb"
	"github.com/luxfi/geth/core/types"
	"github.com/luxfi/geth/core/vm"
	"github.com/stretchr/testify/require"
)

// Callable is the log-emitting contract from blockchain_log_test.go: Call() emits
// the Called() event (a LOG), so contract-call blocks carry logs and exercise the
// receipt-trie/bloom parity that pure transfers do not.
const (
	wiringCallableABI = "[{\"anonymous\":false,\"inputs\":[],\"name\":\"Called\",\"type\":\"event\"},{\"inputs\":[],\"name\":\"Call\",\"outputs\":[],\"stateMutability\":\"nonpayable\",\"type\":\"function\"}]"
	wiringCallableBin = "6080604052348015600f57600080fd5b5060998061001e6000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c806334e2292114602d575b600080fd5b60336035565b005b7f81fab7a4a0aa961db47eefc81f143a5220e8c8495260dd65b1356f1d19d3c7b860405160405180910390a156fea2646970667358221220029436d24f3ac598ceca41d4d712e13ced6d70727f4cdc580667de66d2f51d8b64736f6c63430008010033"
)

// wiringChain builds a realistic multi-sender chain: block 0 deploys Callable;
// every later block mixes transfers between several funded accounts with calls to
// Callable (logs) and a same-sender burst — a genuinely parallelizable, contract-
// heavy, log-bearing workload. It returns the gspec and the generated blocks.
func wiringChain(t *testing.T, nBlocks int) (*Genesis, []*types.Block, common.Address) {
	t.Helper()
	keys := make([]*ecdsa.PrivateKey, 4)
	addrs := make([]common.Address, 4)
	alloc := GenesisAlloc{}
	funds := new(big.Int).Mul(big.NewInt(1000), big.NewInt(params.Ether))
	for i := range keys {
		k, err := crypto.ToECDSA(common.LeftPadBytes(big.NewInt(int64(i+1)).Bytes(), 32))
		require.NoError(t, err)
		keys[i] = k
		addrs[i] = crypto.PubkeyToAddress(k.PublicKey)
		alloc[addrs[i]] = types.Account{Balance: funds}
	}
	gspec := &Genesis{
		Config:  params.TestChainConfig,
		Alloc:   alloc,
		BaseFee: big.NewInt(legacy.BaseFee),
	}
	signer := types.LatestSigner(gspec.Config)
	parsed, err := abi.JSON(strings.NewReader(wiringCallableABI))
	require.NoError(t, err)
	callData, err := parsed.Pack("Call")
	require.NoError(t, err)

	contractAddr := crypto.CreateAddress(crypto.PubkeyToAddress(keys[0].PublicKey), 0)

	nonces := make([]uint64, len(keys))
	price := big.NewInt(legacy.BaseFee)
	engine := dummy.NewCoinbaseFaker()
	_, blocks, _, err := GenerateChainWithGenesis(gspec, engine, nBlocks, 10, func(i int, b *BlockGen) {
		add := func(from int, to *common.Address, val *big.Int, gas uint64, data []byte) {
			var tx *types.Transaction
			if to == nil {
				tx = types.NewContractCreation(nonces[from], val, gas, price, data)
			} else {
				tx = types.NewTransaction(nonces[from], *to, val, gas, price, data)
			}
			signed, err := types.SignTx(tx, signer, keys[from])
			require.NoError(t, err)
			b.AddTx(signed)
			nonces[from]++
		}
		if i == 0 {
			add(0, nil, common.Big0, 200000, common.FromHex(wiringCallableBin)) // deploy
			return
		}
		// transfers from every account + contract calls (logs) + a same-sender burst
		for from := range keys {
			to := addrs[(from+1)%len(addrs)]
			add(from, &to, big.NewInt(int64(100+i)), 21000, nil)
			add(from, &contractAddr, common.Big0, 60000, callData) // emits a log
		}
		add(1, &contractAddr, common.Big0, 60000, callData)
		add(1, &contractAddr, common.Big0, 60000, callData)
	})
	require.NoError(t, err)
	return gspec, blocks, contractAddr
}

// insertOn builds a fresh chain over gspec and inserts blocks with the parallel
// flag set to `enabled`, returning the head state root.
func insertOn(t *testing.T, gspec *Genesis, blocks []*types.Block, enabled bool) common.Hash {
	t.Helper()
	parallel.Enabled.Store(enabled)
	cacheConfig := *DefaultCacheConfig
	cacheConfig.SnapshotLimit = 0
	db := rawdb.NewMemoryDatabase()
	chain, err := NewBlockChain(db, &cacheConfig, gspec, dummy.NewCoinbaseFaker(), vm.Config{}, common.Hash{}, false, nil)
	require.NoError(t, err)
	defer chain.Stop()
	n, err := chain.InsertChain(blocks)
	require.NoError(t, err, "InsertChain rejected a block at index %d (enabled=%v)", n, enabled)
	return chain.CurrentBlock().Root
}

// TestProcessWiring_OffVsOn_Equivalent is the headline Process-level proof: the
// same blocks inserted with the flag OFF and with the flag ON commit a byte-
// identical head state root, both pass ValidateState (so receipts/bloom/gas also
// match the headers), and the ON run actually engaged the parallel engine on
// every block (VerifiedBlocks delta == block count) rather than silently falling
// through to sequential.
func TestProcessWiring_OffVsOn_Equivalent(t *testing.T) {
	const n = 6
	gspec, blocks, _ := wiringChain(t, n)
	defer parallel.Enabled.Store(false)

	rootOff := insertOn(t, gspec, blocks, false)

	before := parallel.DefaultMetrics.VerifiedBlocks.Load()
	rootOn := insertOn(t, gspec, blocks, true)
	delta := parallel.DefaultMetrics.VerifiedBlocks.Load() - before

	if rootOn != rootOff {
		t.Fatalf("head root differs OFF=%x ON=%x", rootOff, rootOn)
	}
	if delta != int64(len(blocks)) {
		t.Fatalf("parallel engine engaged on %d/%d blocks (VerifiedBlocks delta); expected every block to commit via ExecuteVerified", delta, len(blocks))
	}
}

// TestProcessWiring_FlagOffNeverEngages proves the default path pays nothing and
// commits nothing through the gate: with the flag OFF, ExecuteVerified is never
// reached, so VerifiedBlocks does not move while the chain still imports cleanly.
func TestProcessWiring_FlagOffNeverEngages(t *testing.T) {
	gspec, blocks, _ := wiringChain(t, 4)
	defer parallel.Enabled.Store(false)
	before := parallel.DefaultMetrics.VerifiedBlocks.Load()
	insertOn(t, gspec, blocks, false)
	if got := parallel.DefaultMetrics.VerifiedBlocks.Load(); got != before {
		t.Fatalf("flag OFF still engaged the parallel commit path: VerifiedBlocks %d -> %d", before, got)
	}
}

// TestProcessWiring_ForgedRootRejectedUnderBothFlags is the fail-closed proof at
// the consensus boundary: a block whose header.Root is forged (differs from the
// true post-tx root by design) is rejected with the flag ON exactly as with the
// flag OFF. With the flag ON, ExecuteVerified sees its local sequential root
// disagree with the forged block.Root() and fails closed to the sequential loop,
// which recomputes the true root; ValidateState then rejects the forged header.
// So a divergent root can never be committed regardless of the flag.
func TestProcessWiring_ForgedRootRejectedUnderBothFlags(t *testing.T) {
	gspec, blocks, _ := wiringChain(t, 2)
	defer parallel.Enabled.Store(false)

	// Forge the first block's state root. Rebuilding from the tampered header
	// yields an internally-consistent block (its hash matches the bad header) that
	// extends genesis, so it passes header verification and reaches Process.
	bad := blocks[0].Header()
	bad.Root = common.HexToHash("0xbadbadbadbadbadbadbadbadbadbadbadbadbadbadbadbadbadbadbadbadbad00")
	forged := types.NewBlockWithHeader(bad).WithBody(*blocks[0].Body())

	for _, enabled := range []bool{false, true} {
		parallel.Enabled.Store(enabled)
		cacheConfig := *DefaultCacheConfig
		cacheConfig.SnapshotLimit = 0
		db := rawdb.NewMemoryDatabase()
		chain, err := NewBlockChain(db, &cacheConfig, gspec, dummy.NewCoinbaseFaker(), vm.Config{}, common.Hash{}, false, nil)
		require.NoError(t, err)
		_, err = chain.InsertChain([]*types.Block{forged})
		if err == nil {
			chain.Stop()
			t.Fatalf("forged-root block was ACCEPTED (enabled=%v) — fail-closed violated", enabled)
		}
		chain.Stop()
	}
}
