// Code generated by rlpgen. DO NOT EDIT.

package customtypes

import (
	"io"

	"github.com/luxfi/geth/rlp"
)

func (obj *HeaderSerializable) EncodeRLP(_w io.Writer) error {
	w := rlp.NewEncoderBuffer(_w)
	_tmp0 := w.List()
	w.WriteBytes(obj.ParentHash[:])
	w.WriteBytes(obj.UncleHash[:])
	w.WriteBytes(obj.Coinbase[:])
	w.WriteBytes(obj.Root[:])
	w.WriteBytes(obj.TxHash[:])
	w.WriteBytes(obj.ReceiptHash[:])
	w.WriteBytes(obj.Bloom[:])
	if obj.Difficulty == nil {
		_, _ = w.Write(rlp.EmptyString)
	} else {
		if obj.Difficulty.Sign() == -1 {
			return rlp.ErrNegativeBigInt
		}
		w.WriteBigInt(obj.Difficulty)
	}
	if obj.Number == nil {
		_, _ = w.Write(rlp.EmptyString)
	} else {
		if obj.Number.Sign() == -1 {
			return rlp.ErrNegativeBigInt
		}
		w.WriteBigInt(obj.Number)
	}
	w.WriteUint64(obj.GasLimit)
	w.WriteUint64(obj.GasUsed)
	w.WriteUint64(obj.Time)
	w.WriteBytes(obj.Extra)
	w.WriteBytes(obj.MixDigest[:])
	w.WriteBytes(obj.Nonce[:])
	_tmp1 := obj.BaseFee != nil
	_tmp2 := obj.BlockGasCost != nil
	_tmp3 := obj.BlobGasUsed != nil
	_tmp4 := obj.ExcessBlobGas != nil
	_tmp5 := obj.ParentBeaconRoot != nil
	_tmp6 := obj.RequestsHash != nil
	_tmp7 := obj.ExtDataHash != nil
	_tmp8 := obj.ExtDataGasUsed != nil
	if _tmp1 || _tmp2 || _tmp3 || _tmp4 || _tmp5 || _tmp6 || _tmp7 || _tmp8 {
		if obj.BaseFee == nil {
			_, _ = w.Write(rlp.EmptyString)
		} else {
			if obj.BaseFee.Sign() == -1 {
				return rlp.ErrNegativeBigInt
			}
			w.WriteBigInt(obj.BaseFee)
		}
	}
	if _tmp2 || _tmp3 || _tmp4 || _tmp5 || _tmp6 || _tmp7 || _tmp8 {
		if obj.BlockGasCost == nil {
			_, _ = w.Write(rlp.EmptyString)
		} else {
			if obj.BlockGasCost.Sign() == -1 {
				return rlp.ErrNegativeBigInt
			}
			w.WriteBigInt(obj.BlockGasCost)
		}
	}
	if _tmp3 || _tmp4 || _tmp5 || _tmp6 || _tmp7 || _tmp8 {
		if obj.BlobGasUsed == nil {
			_, _ = w.Write([]byte{0x80})
		} else {
			w.WriteUint64((*obj.BlobGasUsed))
		}
	}
	if _tmp4 || _tmp5 || _tmp6 || _tmp7 || _tmp8 {
		if obj.ExcessBlobGas == nil {
			_, _ = w.Write([]byte{0x80})
		} else {
			w.WriteUint64((*obj.ExcessBlobGas))
		}
	}
	if _tmp5 || _tmp6 || _tmp7 || _tmp8 {
		if obj.ParentBeaconRoot == nil {
			_, _ = w.Write([]byte{0x80})
		} else {
			w.WriteBytes(obj.ParentBeaconRoot[:])
		}
	}
	if _tmp6 || _tmp7 || _tmp8 {
		if obj.RequestsHash == nil {
			_, _ = w.Write([]byte{0x80})
		} else {
			w.WriteBytes(obj.RequestsHash[:])
		}
	}
	if _tmp7 || _tmp8 {
		if obj.ExtDataHash == nil {
			_, _ = w.Write([]byte{0x80})
		} else {
			w.WriteBytes(obj.ExtDataHash[:])
		}
	}
	if _tmp8 {
		if obj.ExtDataGasUsed == nil {
			_, _ = w.Write(rlp.EmptyString)
		} else {
			if obj.ExtDataGasUsed.Sign() == -1 {
				return rlp.ErrNegativeBigInt
			}
			w.WriteBigInt(obj.ExtDataGasUsed)
		}
	}
	w.ListEnd(_tmp0)
	return w.Flush()
}
