name: Release

on:
  push:
    tags:
      - "*"

jobs:
  test:
    uses: ./.github/workflows/tests.yml

  release:
    needs: [test]
    uses: ./.github/workflows/release-binaries.yml
    secrets: inherit